# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# 显式收集 core 模块的所有子模块
core_submodules = [
    'core',
    'core.builder',
    'core.data_aggregator',
    'core.decision_engine',
    'core.dictionary_manager',
    'core.exceptions',
    'core.extractor',
    'core.models',
    'core.orchestrator',
    'core.pack_builder',
    'core.quest_converter',
    'core.term_database',
    'core.translator',
    'core.workflow',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('dist/updater.exe', '.')],
    hiddenimports=core_submodules + [
        'psutil',
        'collections',
        'tkinter',
        'ttkbootstrap',
        'requests',
        'charset_normalizer',
        'certifi',
        'idna',
        'urllib3',
        'openai',
        'httpx',
        'gui',
        'gui.main_window',
        'gui.settings_window',
        'gui.settings_components.basic_settings',
        'gui.settings_components.ai_settings',
        'gui.settings_components.resource_pack_settings',
        'gui.settings_components.github_settings',
        'gui.settings_components.advanced_settings',
        'gui.tab_pack_settings',
        'gui.tab_settings_unified',
        'gui.custom_widgets',
        'gui.ui_utils',
        'gui.dialogs',
        'gui.translation_workbench',
        'gui.find_replace_dialog',
        'gui.theme_utils',
        'gui.dictionary_search_window',
        'gui.user_dictionary_editor',
        'gui.quest_workflow_manager',
        'gui.comprehensive_processing_dialog',
        'gui.enhanced_comprehensive_processing',
        'gui.github_upload_ui',
        'gui.dialog.github_version_select',
        'services',
        'services.ai_translator',
        'services.github_service',
        'services.punctuation_corrector',
        'services.space_remover',
        'utils',
        'utils.config_manager',
        'utils.logger_setup',
        'utils.file_utils',
        'utils.error_logger',
        'utils.dictionary_searcher',
        'utils.update_checker',
        'utils.session_manager',
        'utils.retry_logic',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='Modpack-Localizer-Pro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
