"""项目全局常量定义。"""

# 线程池大小限制
EXTRACTOR_SCAN_MAX_WORKERS = 8
EXTRACTOR_FINGERPRINT_MAX_WORKERS = 32
TRANSLATOR_MAX_WORKERS = 8
TRANSLATOR_SERIAL_THRESHOLD = 3  # 命名空间数量低于此值时使用串行处理

# 缓存大小
TRANSLATOR_VALIDATION_CACHE_SIZE = 131072  # 128K 条

# AI 翻译
AI_TRANSLATOR_MAX_CACHE_SIZE = 10000
AI_TRANSLATOR_MAX_ATTEMPTS = 5

# 日志
ERROR_LOG_MAX_DAYS = 10
ERROR_LOG_CLEAN_INTERVAL_SECONDS = 3600  # 每小时清理一次

# 局域网传输
LAN_UDP_PORT = 19871
LAN_HTTP_PORT_START = 19872
LAN_HTTP_PORT_END = 19882
LAN_BROADCAST_INTERVAL = 1.0
LAN_BROADCAST_COUNT = 15

# JAR 文件读取缓冲区大小
JAR_READ_CHUNK_SIZE = 65536  # 64KB
